# Generated by Django 3.2.5 on 2021-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('comnpany', models.CharField(max_length=100)),
            ],
        ),
    ]
